# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


# externals
import collections
import json

# support
import journal


# the journal device that reaches the browser
class Journal(journal.device):
    """
    A journal device that keeps a bounded history of records and publishes them to live clients

    Installed on the chronicler, it sees every entry the server flushes, from python and from
    C++, and every entry the crews produce, since the nexus replays those into the server's
    journal. Each entry is mirrored to the device that was installed before it, so the terminal
    remains the record, recorded into a history that a newcomer can be sent, and queued for
    publication on the {journal} topic of the event hub. Records travel in batches: the first
    entry after a quiet spell arms a one-shot alarm, and everything that accumulates before it
    fires goes out as one frame
    """

    # constants
    # the hub topic the records ride on
    topic = "journal"
    # the frame name, so a client can tell a batch of records from anything else
    event = "journal"
    # the origin fields a replayed record carries in its notes
    origin = ("pid", "seq", "time")

    # interface
    def alert(self, entry):
        """
        Generate an alert

        Alerts are user-facing; they are generated by {info}, {warning}, and {error}
        """
        # deliver
        return self._deliver(entry=entry, sink="alert")

    def help(self, entry):
        """
        Generate a help screen
        """
        # deliver
        return self._deliver(entry=entry, sink="help")

    def memo(self, entry):
        """
        Issue a memo

        Memos are developer-facing; they are generated by {debug} and {firewall}
        """
        # deliver
        return self._deliver(entry=entry, sink="memo")

    def opening(self):
        """
        Frame the history for a newcomer, or nothing if there is none
        """
        # if there is no history
        if not self.history:
            # there is nothing to open with
            return None
        # frame it as one batch
        return self._frame(records=self.history)

    def stamp(self, entry, sink):
        """
        Build the record for {entry} bound for {sink}

        An entry the nexus replayed from a crew member carries its origin in its notes; it is
        lifted back into the envelope, so a client sees one record shape whatever the origin
        """
        # build the record with my own sequence number
        record = journal.record.stamp(entry=entry, sink=sink, seq=self.seq + 1)
        # the notes
        notes = record.notes
        # if the entry came from somewhere else
        if all(field in notes for field in self.origin):
            # attempt to
            try:
                # lift the origin out of the notes
                pid = int(notes[self.origin[0]])
                seq = int(notes[self.origin[1]])
                stamp = float(notes[self.origin[2]])
            # if the fields are not what a replay writes, they are somebody's own notes
            except ValueError:
                # leave them alone
                pass
            # otherwise
            else:
                # the envelope is the origin's
                record.pid = pid
                record.seq = seq
                record.time = stamp
                # and the notes are what the origin flushed
                for field in self.origin:
                    # so drop the copies
                    del notes[field]
                # all done
                return record
        # the entry is mine; consume the sequence number
        self.seq += 1
        # all done
        return record

    # metamethods
    def __init__(
        self, server, mirror=None, capacity=2048, latency=None, name="journal", **kwds
    ):
        # chain up
        super().__init__(name=name, **kwds)
        # the server whose hub, dispatcher, and stream framing i use
        self.server = server
        # the device that also gets every entry, if any
        self.mirror = mirror
        # how long to accumulate records before publishing a batch
        self.latency = latency
        # the sequence number of the last record of my own
        self.seq = 0
        # the records a newcomer is sent
        self.history = collections.deque(maxlen=capacity)
        # the records waiting to be published
        self.pending = []
        # the channels that have spoken, as (severity, name) pairs
        self.channels = set()
        # whether the alarm that publishes the pending records is armed
        self.armed = False
        # whether a batch is being published right now
        self.publishing = False
        # all done
        return

    # implementation details
    def _deliver(self, entry, sink):
        """
        Hand {entry} to the mirror, record it, and queue it for publication
        """
        # if there is a mirror
        if self.mirror is not None:
            # it gets the entry unchanged, through the same sink
            getattr(self.mirror, sink)(entry=entry)
        # build the record
        record = self.stamp(entry=entry, sink=sink)
        # remember it
        self.history.append(record)
        # and the channel that produced it
        self.channels.add((record.severity, record.channel))
        # an entry flushed while a batch is going out is recorded but not queued, so a hub
        # that speaks up while draining a slow client cannot loop back into itself
        if self.publishing:
            # all done
            return self
        # queue it
        self.pending.append(record)
        # and make sure it goes out
        self._arm()
        # all done
        return self

    def _arm(self):
        """
        Schedule the publication of the pending records, unless it is already scheduled
        """
        # if the alarm is armed
        if self.armed:
            # nothing to do
            return
        # arm it
        self.server.dispatcher.alarm(interval=self.latency, call=self._publish)
        # and remember
        self.armed = True
        # all done
        return

    def _publish(self, timestamp, **kwds):
        """
        Publish the pending records as one frame

        N.B.: this is an alarm handler; returning {None} keeps it from being rescheduled
        """
        # the alarm has fired
        self.armed = False
        # if nothing is pending
        if not self.pending:
            # there is nothing to do
            return None
        # take the batch
        batch = self.pending
        # and start a fresh one
        self.pending = []
        # frame it
        frame = self._frame(records=batch)
        # mark the publication, so entries it provokes stay out of the queue
        self.publishing = True
        # carefully
        try:
            # publish; every record is content, so nothing coalesces
            self.server.hub.publish(frame, topic=self.topic)
        # whatever happens
        finally:
            # the publication is over
            self.publishing = False
        # do not reschedule
        return None

    def _frame(self, records):
        """
        Render {records} as one event frame
        """
        # the payload: a list of wire objects
        payload = json.dumps([record.raw() for record in records], ensure_ascii=False)
        # a stream, for the framing
        stream = self.server.eventStream(server=self.server)
        # frame the payload under my event name
        return stream.event(payload, name=self.event)


# end of file
