# -*- graphql -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2024 all rights reserved


schema {
  query: Query
  mutation: Mutation
}


# the top level query
type Query {
  # server version information
  version: Version!

  # the qed session
  qed: QED!

  # retrieve the contents of a data archive
  contents(archive: String!, path: String!): [Item]
  # attempt to guess as much about a dataset as possible
  discover(archive: String!, uri: String!, module: String!) : ProductMetadata
  # collect data values as represented by the available channels at a particular pixel
  sample(dataset: ID, line: Int!, sample: Int!): Sample!
  # generate candidate shapes given the size of a raster
  guessShape(size: String! aspect: String!): [Shape]
}


# server version
type Version {
  major: Int!
  minor: Int!
  micro: Int!
  revision: String!
}

# the qed session
type QED implements Node {
  # the id
  id: ID!
  # the visible viewports
  views: [View]
  # the connected data archives
  archives: [Archive]
  # the connected readers
  readers: [Reader]
}


# viewports
type View implements Node {
  # ids
  id: ID!
  name: ID!
  session: String!
  # dataset selection
  selections: [Selector]
  # visualization pipeline
  reader: Reader
  dataset: Dataset
  channel: Channel
  # dataset specific viewing options
  measure: DatasetMeasure
  sync: DatasetSync
  zoom: DatasetZoom
}

# archives
type Archive implements Node {
  # id
  id: ID!
  # the name of the archive
  name: String!
  # its uri
  uri: String!
  # the supported readers
  readers: [String!]!
}

# archive contents
type Item implements Node {
  # id
  id: ID!
  # the name of the item
  name: String!
  # its uri
  uri: String!
  # a marker for directories
  isFolder: Boolean!
}

# product metadata
type ProductMetadata implements Node {
  # id
  id: ID!
  # the product uri
  uri: String!
  # product type
  product: String
  # the size of the data product in bytes; float because int is 32 bit
  bytes: Float
  # the number of cells in the data product; float because int is 32 bit
  cells: Float
  # shape
  shape: [Int]
  # data type
  type: String
}

# readers
type Reader implements Node {
  # ids
  id: ID!
  name: ID!
  # the full path to the supporting file
  uri: String!
  # the prefix of the data request url
  api: String!
  # the catalog of dataset selectors and their legal values
  selectors: [Selectors]!
  # the catalog of dataset selectors and their available values
  available: [Selectors]!
  # the actual datasets contained in the source
  datasets: [Dataset]!
}


# datasets
type Dataset implements Node {
  # ids
  id: ID!
  name: ID!
  # metadata
  channels: [Channel]!
  datatype: String!
  selector: [Selector]!
  shape: [Int!]!
  origin: [Int!]!
  tile: [Int!]!
}

# channel
type Channel implements Node {
  # ids
  id: ID!
  name: ID!
  tag: String!
  # the viz pipeline controllers
  controllers: [Controller]!
}

# selectors
type Selectors {
  # name
  name: String!
  values: [String!]!
}


type Selector {
  # name
  name: String!
  value: String!
}

# data exchanges
type Sample {
  pixel: [Int]
  value: [ChannelRep]
}

type ChannelRep {
  channel: String
  reps: [ChannelValue]
}

type ChannelValue {
  rep: String
  units: String
}


# visualization pipeline
type VisualizationPipeline {
  dataset: ID
  channel: String!
  controllers: [Controller!]!
}

# controllers
type RangeController implements Node {
  id: ID!
  dirty: Boolean!
  slot: String!
  min: Float!
  max: Float!
  low: Float!
  high: Float!
}

type ValueController implements Node {
  id: ID!
  dirty: Boolean!
  slot: String!
  min: Float!
  max: Float!
  value: Float!
}

# put them all together
union Controller = RangeController | ValueController

# viewport properties that are persisted with datasets
type DatasetView implements Node {
  id: ID!
  name: ID!
  measure: DatasetMeasure
  sync: DatasetSync
  zoom: DatasetZoom
}

type DatasetMeasure implements Node {
  id: ID!
  name: ID!
  dirty: Boolean
  active: Boolean
  path: [Pixel]
  closed: Boolean
  selection: [Int]
}

type DatasetSync implements Node {
  id: ID!
  name: ID!
  dirty: Boolean
  channel: Boolean
  zoom: Boolean
  scroll: Boolean
  path: Boolean
  offsets: Pixel
}

type DatasetZoom implements Node {
  id: ID!
  name: ID!
  dirty: Boolean
  coupled: Boolean
  horizontal: Float
  vertical: Float
}

# pixel
type Pixel {
  x: Int
  y: Int
}

# raster shape
type Shape {
  lines: String!
  samples: String!
}


# mutations
type Mutation {
  # viewports
  viewCollapse(viewport: Int!): ViewInfo!
  viewSplit(viewport: Int!): ViewInfo!
  viewSelectReader(viewport: Int!, reader: String!): ViewInfo!
  viewToggleCoordinate(selection: ViewSelectorInput!): ViewInfo!
  viewChannelSet(selection: ViewSelectorInput!): ViewInfos!
  viewPersist(dummy: ID): PersistInfo
  # measure layer
  viewMeasureAnchorAdd(viewport: Int!, x: Int!, y: Int!, index: Int): DatasetMeasureInfos!
  viewMeasureAnchorExtendSelection(viewport: Int!, index: Int!): DatasetMeasureInfo!
  viewMeasureAnchorMove(viewport: Int!, handle: Int!, dx: Int!, dy: Int!): DatasetMeasureInfo!
  viewMeasureAnchorPlace(viewport: Int!, handle: Int!, x: Int!, y: Int!): DatasetMeasureInfo!
  viewMeasureAnchorRemove(viewport: Int!, anchor: Int!): DatasetMeasureInfo!
  viewMeasureAnchorSplit(viewport: Int!, anchor: Int!): DatasetMeasureInfo!
  viewMeasureAnchorToggleSelection(viewport: Int!, index: Int!): DatasetMeasureInfo!
  viewMeasureAnchorToggleSelectionMulti(viewport: Int!, index: Int!): DatasetMeasureInfo!
  viewMeasureToggleLayer(viewport: Int!, reader: String!): DatasetMeasureInfo!
  viewMeasureToggleClosedPath(viewport: Int!): DatasetMeasureInfos!
  viewMeasureReset(viewport: Int!): DatasetMeasureInfo!
  # sync
  viewSyncReset(viewport: Int!): DatasetSyncInfo!
  viewSyncToggleAll(viewport: Int!, aspect: String!): DatasetSyncInfos!
  viewSyncToggleViewport(viewport: Int!, aspect: String!): DatasetSyncInfo!
  viewSyncUpdateOffset(viewport: Int!, x: Int!, y: Int!): DatasetSyncInfo!
  # zoom
  viewZoomSetLevel(viewport: Int!, horizontal: Float!, vertical: Float!): DatasetZoomInfos!
  viewZoomToggleCoupled(viewport: Int!): DatasetZoomInfos!
  viewZoomReset(viewport: Int!): DatasetZoomInfo!

  # data archive connections
  connectArchive(name: String!, uri: String!): ArchiveInfo!
  disconnectArchive(uri: String!): ArchiveInfo!
  # reader connections
  connectReader(spec: ReaderInput!): ReaderInfo!
  disconnectReader(name: String!): ReaderInfo!

  # updates to the viz pipeline
  resetRangeController(controller: RangeControllerResetInput!): RangeControllerInfo!
  updateRangeController(range: RangeControllerUpdateInput!): RangeControllerInfo!
  resetValueController(controller: ValueControllerResetInput!): ValueControllerInfo!
  updateValueController(value: ValueControllerUpdateInput!): ValueControllerInfo!
}

type PersistInfo {
  # the store id
  id: ID
}

# viewport management
# request payloads
input ViewSelectorInput {
  # the viewport
  viewport: Int!
  # the reader
  reader: String!
  # the selector; axis or channel name
  selector: String!
  # the value
  value: String!
}

# the response payload
type ViewInfo {
  # the view settings
  view: View
}

type ViewInfos {
  # the view settings
  views: [View]
}

# the measure layer state response payload
type DatasetMeasureInfo {
  # the measure layer settings
  measure: DatasetMeasure
}

type DatasetMeasureInfos {
  # the measure layer settings
  measures: [DatasetMeasure]
}

# the sync state response payload
type DatasetSyncInfo {
  # the sync table
  sync: DatasetSync
}

# the sync state response payload
type DatasetSyncInfos {
  # the sync tables
  sync: [DatasetSync]
}

# the measure layer state response payload
type DatasetZoomInfo {
  # the zoom settings
  zoom: DatasetZoom
}

# the measure layer state response payload
type DatasetZoomInfos {
  # the zoom settings
  zoom: [DatasetZoom]
}

# support for connecting and disconnecting data archives
# the response payload
type ArchiveInfo {
  # the new archive
  archive: Archive
}

# support for connecting and disconnecting data readers
# the request payload
input ReaderInput {
  reader: String!
  name: String!
  uri: String!
  lines: String
  samples: String
  cell: String
}

# the response payload
type ReaderInfo {
  # the new archive
  reader: Reader
}


# support for updating range controllers
# the reset request payload
input RangeControllerResetInput {
  # the dataset
  viewport: Int!
  # the channel
  channel: String!
  # the controller name
  controller: String!
}

# the update range request payload
input RangeControllerUpdateInput {
  # the viewport
  viewport: Int!
  # the channel
  channel: String!
  # the controller name
  controller: String!
  # the parameters
  min: Float!
  low: Float!
  high: Float!
  max: Float!
}

# the response payload
type RangeControllerInfo {
  # the view
  view: View!
  # the updated controller
  controller: RangeController!
}


# support for updating value controllers
# the reset request payload
input ValueControllerResetInput {
  # the dataset
  viewport: Int!
  # the channel
  channel: String!
  # the controller name
  controller: String!
}

# the update value request payload
input ValueControllerUpdateInput {
  # the viewport
  viewport: Int!
  # the channel
  channel: String!
  # the controller name
  controller: String!
  # the parameters
  min: Float!
  value: Float!
  max: Float!
}

# the response payload
type ValueControllerInfo {
  # the view
  view: View!
  # the updated controller
  controller: ValueController!
}


# interfaces
# the node interface
interface Node {
  # the node relay id
  id: ID!
}


# boilerplate for connections
type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}


# end of file
