# -*- graphql -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2021 all rights reserved


schema {
  query: Query
}


# the top level query
type Query {
  # information about the known data sets
  datasets: Datasets
  # server version information
  version: Version
}


# server version
type Version {
  major: Int!
  minor: Int!
  micro: Int!
  revision: String!
}


# readers
type Reader implements Node {
  # ids
  id: ID!
  uuid: ID!
  # the full path to the supporting file
  uri: String!
  selectors: [SelectorDef]!
}


# selectors
type SelectorDef {
  # name
  name: String
  values: [String]
}


# datasets
type Datasets {
  # the id
  id: ID!
}


# connections
type ReaderConnection {
  edges: [ReaderEdge]
  pageInfo: PageInfo!
}

type ReaderEdge {
  node: Reader
  cursor: String!
}


# interfaces
# the node interface
interface Node {
  # the node relay id
  id: ID!
  # and the uuid of the pyre object
  uuid: ID!
}


# boilerplate for connections
type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}


# end of file
