# -*- yaml -*-
# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


name: qed

channels:
  - conda-forge

dependencies:
  # tools for building from source
  - binutils
  - git
  - git-lfs
  - gcc
  - gxx
  - make
  - nodejs
  - vim
  # python and runtime packages
  - python
  - graphene
  - pyyaml
  # external libraries
  - hdf5
  - pybind11


# end of file
